# **Text Preprocessing**

### **Cleaning**

In [ ]:
!pip install nltk Sastrawi rapidfuzz

Requirement already satisfied: nltk in /usr/local/lib/python3.12/dist-packages (3.9.1)
Requirement already satisfied: Sastrawi in /usr/local/lib/python3.12/dist-packages (1.0.1)
Requirement already satisfied: rapidfuzz in /usr/local/lib/python3.12/dist-packages (3.14.5)
Requirement already satisfied: click in /usr/local/lib/python3.12/dist-packages (from nltk) (8.4.0)
Requirement already satisfied: joblib in /usr/local/lib/python3.12/dist-packages (from nltk) (1.5.3)
Requirement already satisfied: regex>=2021.8.3 in /usr/local/lib/python3.12/dist-packages (from nltk) (2025.11.3)
Requirement already satisfied: tqdm in /usr/local/lib/python3.12/dist-packages (from nltk) (4.67.3)

In [ ]:
import pandas as pd
import re
import string
from nltk.corpus import stopwords
import nltk
from typing import List
from rapidfuzz import process, fuzz

nltk.download('stopwords')

from Sastrawi.StopWordRemover.StopWordRemoverFactory import StopWordRemoverFactory

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

In [ ]:
url='https://docs.google.com/spreadsheets/d/e/2PACX-1vQIcd31RPSNv-B-U2uymfJPK4aBF2LQOoZ1IlfCXdMVBHtgFglps-Jo4DpeFgC5SUyAQjY9h7mZ2lOc/pub?gid=213577436&single=true&output=csv'
df = pd.read_csv(url)
df.head()

         posisi                                          deskripsi   level
0  data analyst  Kualifikasi\n:\nS1 Teknik Industri / Informati...   entry
1  data analyst  Key Responsibilities\nBuild, maintain, and aut...  middle
2  data analyst  Company Description\nAbout Grab and Our Workpl...  senior
3  data analyst  Responsibilities:\nSupporting Accounting Divis...  middle
4  data analyst  Cimol Bojot AA (PT Citarasa Kuliner Indonesia)...  middle

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5169 entries, 0 to 5168
Data columns (total 3 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   posisi     5169 non-null   object
 1   deskripsi  5169 non-null   object
 2   level      5169 non-null   object
dtypes: object(3)
memory usage: 121.3+ KB

Dictionary

In [ ]:
SKILL_DICT = {

    # PROGRAMMING LANGUAGES

    "python": "Python",
    "python3": "Python",
    "py": "Python",
    "golang": "Go",
    "go lang": "Go",
    "go language": "Go",
    "java": "Java",
    "java se": "Java",
    "java ee": "Java EE",
    "kotlin": "Kotlin",
    "scala": "Scala",
    "r language": "R",
    "r programming": "R",
    "r studio": "R",
    "rstudio": "R",
    "julia": "Julia",
    "c programming": "C",
    "c language": "C",
    "c++": "C++",
    "cpp": "C++",
    "c plus plus": "C++",
    "c#": "C#",
    "csharp": "C#",
    "c sharp": "C#",
    ".net": ".NET",
    "dotnet": ".NET",
    "dot net": ".NET",
    "rust": "Rust",
    "ruby": "Ruby",
    "rails": "Ruby on Rails",
    "ruby on rails": "Ruby on Rails",
    "ror": "Ruby on Rails",
    "php": "PHP",
    "perl": "Perl",
    "swift": "Swift",
    "objective-c": "Objective-C",
    "objc": "Objective-C",
    "dart": "Dart",
    "elixir": "Elixir",
    "erlang": "Erlang",
    "haskell": "Haskell",
    "lua": "Lua",
    "matlab": "MATLAB",
    "fortran": "Fortran",
    "cobol": "COBOL",
    "bash": "Bash",
    "shell scripting": "Shell Scripting",
    "shell script": "Shell Scripting",
    "powershell": "PowerShell",

    # WEB FRONTEND

    "html": "HTML",
    "html5": "HTML",
    "css": "CSS",
    "css3": "CSS",
    "javascript": "JavaScript",
    "js": "JavaScript",
    "typescript": "TypeScript",
    "ts": "TypeScript",
    "react": "React",
    "react.js": "React",
    "reactjs": "React",
    "react js": "React",
    "react native": "React Native",
    "vue": "Vue.js",
    "vue.js": "Vue.js",
    "vuejs": "Vue.js",
    "angular": "Angular",
    "angularjs": "Angular",
    "angular.js": "Angular",
    "next.js": "Next.js",
    "nextjs": "Next.js",
    "nuxt": "Nuxt.js",
    "nuxt.js": "Nuxt.js",
    "svelte": "Svelte",
    "jquery": "jQuery",
    "bootstrap": "Bootstrap",
    "tailwind": "Tailwind CSS",
    "tailwindcss": "Tailwind CSS",
    "tailwind css": "Tailwind CSS",
    "sass": "SASS",
    "scss": "SCSS",
    "less": "LESS",
    "webpack": "Webpack",
    "vite": "Vite",
    "graphql": "GraphQL",

    # WEB BACKEND

    "node.js": "Node.js",
    "nodejs": "Node.js",
    "node js": "Node.js",
    "express": "Express.js",
    "express.js": "Express.js",
    "fastapi": "FastAPI",
    "fast api": "FastAPI",
    "flask": "Flask",
    "django": "Django",
    "spring": "Spring",
    "spring boot": "Spring Boot",
    "springboot": "Spring Boot",
    "laravel": "Laravel",
    "symfony": "Symfony",
    "codeigniter": "CodeIgniter",
    "asp.net": "ASP.NET",
    "aspnet": "ASP.NET",
    "nestjs": "NestJS",
    "nest.js": "NestJS",
    "gin": "Gin",
    "echo": "Echo",
    "fiber": "Fiber",
    "grpc": "gRPC",
    "rest api": "REST API",
    "restful api": "REST API",
    "restful": "REST API",
    "rest": "REST API",
    "api": "API",
    "web service": "Web Service",
    "webservice": "Web Service",
    "soap": "SOAP",
    "microservices": "Microservices",
    "micro services": "Microservices",
    "microservice": "Microservices",


    # MOBILE

    "android": "Android",
    "android development": "Android",
    "ios": "iOS",
    "ios development": "iOS",
    "flutter": "Flutter",
    "xamarin": "Xamarin",
    "ionic": "Ionic",
    "cordova": "Cordova",
    "android studio": "Android Studio",


    # DATABASE – SQL

    "sql": "SQL",
    "mysql": "MySQL",
    "my sql": "MySQL",
    "postgresql": "PostgreSQL",
    "postgres": "PostgreSQL",
    "postgre sql": "PostgreSQL",
    "postgre": "PostgreSQL",
    "pgsql": "PostgreSQL",
    "microsoft sql server": "SQL Server",
    "ms sql": "SQL Server",
    "sql server": "SQL Server",
    "mssql": "SQL Server",
    "oracle": "Oracle DB",
    "oracle db": "Oracle DB",
    "oracle database": "Oracle DB",
    "oracle erp": "Oracle ERP",
    "sqlite": "SQLite",
    "mariadb": "MariaDB",
    "maria db": "MariaDB",
    "db2": "IBM DB2",
    "ibm db2": "IBM DB2",


    # DATABASE – NoSQL

    "mongodb": "MongoDB",
    "mongo db": "MongoDB",
    "mongo": "MongoDB",
    "redis": "Redis",
    "cassandra": "Cassandra",
    "apache cassandra": "Cassandra",
    "elasticsearch": "Elasticsearch",
    "elastic search": "Elasticsearch",
    "es": "Elasticsearch",
    "couchdb": "CouchDB",
    "neo4j": "Neo4j",
    "dynamodb": "DynamoDB",
    "dynamo db": "DynamoDB",
    "firestore": "Firestore",
    "firebase": "Firebase",
    "hbase": "HBase",
    "influxdb": "InfluxDB",


    # DATA ANALYSIS & BI TOOLS

    "excel": "Excel",
    "ms excel": "Excel",
    "microsoft excel": "Excel",
    "spreadsheet": "Excel",
    "google sheets": "Google Sheets",
    "gsheet": "Google Sheets",
    "google spreadsheet": "Google Sheets",
    "power bi": "Power BI",
    "powerbi": "Power BI",
    "power-bi": "Power BI",
    "pbi": "Power BI",
    "tableau": "Tableau",
    "tableau desktop": "Tableau",
    "tableau public": "Tableau",
    "looker": "Looker",
    "looker studio": "Looker Studio",
    "google data studio": "Looker Studio",
    "data studio": "Looker Studio",
    "metabase": "Metabase",
    "superset": "Apache Superset",
    "apache superset": "Apache Superset",
    "zoho analytics": "Zoho Analytics",
    "qlik": "QlikView",
    "qlikview": "QlikView",
    "qlik sense": "Qlik Sense",
    "sisense": "Sisense",
    "sap business objects": "SAP BusinessObjects",
    "cognos": "IBM Cognos",
    "domo": "Domo",
    "grafana": "Grafana",
    "kibana": "Kibana",


    # DATA VISUALIZATION

    "data visualization": "Data Visualization",
    "visualisasi data": "Data Visualization",
    "data viz": "Data Visualization",
    "alat visualisasi data": "Data Visualization",
    "dashboard": "Dashboard",
    "reporting": "Reporting",
    "laporan": "Reporting",
    "matplotlib": "Matplotlib",
    "seaborn": "Seaborn",
    "plotly": "Plotly",
    "bokeh": "Bokeh",
    "d3.js": "D3.js",
    "d3js": "D3.js",
    "echarts": "ECharts",
    "ggplot": "ggplot2",
    "ggplot2": "ggplot2",


    # DATA ENGINEERING & ETL

    "etl": "ETL",
    "elt": "ELT",
    "data pipeline": "Data Pipeline",
    "data warehousing": "Data Warehouse",
    "data warehouse": "Data Warehouse",
    "data lake": "Data Lake",
    "dbt": "dbt",
    "apache spark": "Apache Spark",
    "spark": "Apache Spark",
    "pyspark": "PySpark",
    "hadoop": "Hadoop",
    "apache hadoop": "Hadoop",
    "hive": "Hive",
    "apache hive": "Hive",
    "kafka": "Kafka",
    "apache kafka": "Kafka",
    "apache airflow": "Apache Airflow",
    "airflow": "Apache Airflow",
    "luigi": "Luigi",
    "nifi": "Apache NiFi",
    "apache nifi": "Apache NiFi",
    "flink": "Apache Flink",
    "apache flink": "Apache Flink",
    "databricks": "Databricks",
    "snowflake": "Snowflake",
    "bigquery": "BigQuery",
    "google bigquery": "BigQuery",
    "redshift": "Amazon Redshift",
    "amazon redshift": "Amazon Redshift",
    "azure synapse": "Azure Synapse",
    "synapse analytics": "Azure Synapse",
    "talend": "Talend",
    "informatica": "Informatica",
    "pentaho": "Pentaho",
    "fivetran": "Fivetran",
    "stitch": "Stitch",


    # DATA SCIENCE & ML

    "machine learning": "Machine Learning",
    "ml": "Machine Learning",
    "deep learning": "Deep Learning",
    "dl": "Deep Learning",
    "data science": "Data Science",
    "artificial intelligence": "Artificial Intelligence",
    "ai": "Artificial Intelligence",
    "natural language processing": "NLP",
    "nlp": "NLP",
    "computer vision": "Computer Vision",
    "cv": "Computer Vision",
    "tensorflow": "TensorFlow",
    "tensor flow": "TensorFlow",
    "tf": "TensorFlow",
    "pytorch": "PyTorch",
    "torch": "PyTorch",
    "keras": "Keras",
    "scikit-learn": "Scikit-learn",
    "sklearn": "Scikit-learn",
    "scikit learn": "Scikit-learn",
    "xgboost": "XGBoost",
    "lightgbm": "LightGBM",
    "catboost": "CatBoost",
    "numpy": "NumPy",
    "pandas": "Pandas",
    "scipy": "SciPy",
    "hugging face": "Hugging Face",
    "llm": "LLM",
    "generative ai": "Generative AI",
    "gen ai": "Generative AI",
    "prompt engineering": "Prompt Engineering",
    "mlops": "MLOps",
    "feature engineering": "Feature Engineering",
    "analisis data": "Data Analysis",
    "data analysis": "Data Analysis",
    "statistical analysis": "Statistical Analysis",
    "analisis statistik": "Statistical Analysis",
    "statistics": "Statistics",
    "statistika": "Statistics",
    "regression": "Regression",
    "classification": "Classification",
    "clustering": "Clustering",
    "forecasting": "Forecasting",


    # CLOUD

    "aws": "AWS",
    "amazon web services": "AWS",
    "amazon aws": "AWS",
    "gcp": "GCP",
    "google cloud": "GCP",
    "google cloud platform": "GCP",
    "azure": "Azure",
    "microsoft azure": "Azure",
    "alibaba cloud": "Alibaba Cloud",
    "aliyun": "Alibaba Cloud",
    "digital ocean": "DigitalOcean",
    "digitalocean": "DigitalOcean",
    "heroku": "Heroku",
    "vercel": "Vercel",
    "netlify": "Netlify",
    "cloudflare": "Cloudflare",


    # DEVOPS & CI/CD

    "docker": "Docker",
    "kubernetes": "Kubernetes",
    "k8s": "Kubernetes",
    "helm": "Helm",
    "terraform": "Terraform",
    "ansible": "Ansible",
    "jenkins": "Jenkins",
    "gitlab ci": "GitLab CI/CD",
    "gitlab ci/cd": "GitLab CI/CD",
    "github actions": "GitHub Actions",
    "github action": "GitHub Actions",
    "circleci": "CircleCI",
    "travis ci": "Travis CI",
    "travis": "Travis CI",
    "ci/cd": "CI/CD",
    "cicd": "CI/CD",
    "ci cd": "CI/CD",
    "devops": "DevOps",
    "devsecops": "DevSecOps",
    "sre": "SRE",
    "site reliability engineering": "SRE",
    "linux": "Linux",
    "ubuntu": "Linux",
    "centos": "Linux",
    "debian": "Linux",
    "unix": "Unix",
    "nginx": "Nginx",
    "apache": "Apache",
    "apache web server": "Apache",
    "haproxy": "HAProxy",
    "load balancer": "Load Balancer",
    "prometheus": "Prometheus",
    "grafana": "Grafana",
    "elk stack": "ELK Stack",
    "logstash": "Logstash",
    "splunk": "Splunk",
    "new relic": "New Relic",
    "datadog": "Datadog",


    # VERSION CONTROL

    "git": "Git",
    "github": "GitHub",
    "gitlab": "GitLab",
    "bitbucket": "Bitbucket",
    "svn": "SVN",
    "subversion": "SVN",


    # NETWORKING

    "tcp/ip": "TCP/IP",
    "tcp ip": "TCP/IP",
    "dns": "DNS",
    "dhcp": "DHCP",
    "vpn": "VPN",
    "firewall": "Firewall",
    "bgp": "BGP",
    "ospf": "OSPF",
    "vlan": "VLAN",
    "mpls": "MPLS",
    "sdwan": "SD-WAN",
    "sd-wan": "SD-WAN",
    "cisco": "Cisco",
    "mikrotik": "MikroTik",
    "juniper": "Juniper",
    "fortinet": "Fortinet",
    "palo alto": "Palo Alto",
    "wireshark": "Wireshark",
    "network monitoring": "Network Monitoring",
    "monitoring jaringan": "Network Monitoring",


    # SECURITY

    "cybersecurity": "Cybersecurity",
    "cyber security": "Cybersecurity",
    "information security": "Information Security",
    "keamanan informasi": "Information Security",
    "penetration testing": "Penetration Testing",
    "pentest": "Penetration Testing",
    "pen test": "Penetration Testing",
    "ethical hacking": "Ethical Hacking",
    "vulnerability assessment": "Vulnerability Assessment",
    "soc": "SOC",
    "security operations center": "SOC",
    "siem": "SIEM",
    "owasp": "OWASP",
    "iso 27001": "ISO 27001",
    "iso27001": "ISO 27001",
    "cryptography": "Cryptography",
    "kriptografi": "Cryptography",
    "ssl": "SSL/TLS",
    "tls": "SSL/TLS",
    "ssl/tls": "SSL/TLS",
    "oauth": "OAuth",
    "jwt": "JWT",


    # QA & TESTING

    "software testing": "Software Testing",
    "pengujian perangkat lunak": "Software Testing",
    "manual testing": "Manual Testing",
    "automated testing": "Automated Testing",
    "automation testing": "Automated Testing",
    "selenium": "Selenium",
    "cypress": "Cypress",
    "playwright": "Playwright",
    "jest": "Jest",
    "junit": "JUnit",
    "pytest": "PyTest",
    "mocha": "Mocha",
    "appium": "Appium",
    "jmeter": "JMeter",
    "apache jmeter": "JMeter",
    "postman": "Postman",
    "soapui": "SoapUI",
    "katalon": "Katalon",
    "robot framework": "Robot Framework",
    "unit testing": "Unit Testing",
    "integration testing": "Integration Testing",
    "regression testing": "Regression Testing",
    "performance testing": "Performance Testing",
    "uji kinerja": "Performance Testing",
    "load testing": "Load Testing",
    "test case": "Test Case",
    "test plan": "Test Plan",
    "bug tracking": "Bug Tracking",
    "bug report": "Bug Report",


    # PROJECT MANAGEMENT & AGILE

    "agile": "Agile",
    "scrum": "Scrum",
    "kanban": "Kanban",
    "jira": "Jira",
    "confluence": "Confluence",
    "trello": "Trello",
    "asana": "Asana",
    "notion": "Notion",
    "project management": "Project Management",
    "manajemen proyek": "Project Management",
    "sprint": "Agile",
    "product backlog": "Agile",
    "sdlc": "SDLC",
    "software development life cycle": "SDLC",


    # ERP & CRM

    "sap": "SAP",
    "sap hana": "SAP HANA",
    "sap erp": "SAP ERP",
    "odoo": "Odoo",
    "salesforce": "Salesforce",
    "microsoft dynamics": "Microsoft Dynamics",
    "ms dynamics": "Microsoft Dynamics",
    "zoho": "Zoho CRM",
    "hubspot": "HubSpot",
    "erp": "ERP",
    "crm": "CRM",


    # MICROSOFT

    "microsoft office": "Microsoft Office",
    "ms office": "Microsoft Office",
    "microsoft word": "Microsoft Word",
    "ms word": "Microsoft Word",
    "microsoft powerpoint": "PowerPoint",
    "ms powerpoint": "PowerPoint",
    "powerpoint": "PowerPoint",
    "google workspace": "Google Workspace",
    "gsuite": "Google Workspace",
    "g suite": "Google Workspace",
    "pivot table": "Pivot Table",
    "pivot tables": "Pivot Table",
    "vlookup": "Excel",
    "macro": "Excel Macro",
    "macros": "Excel Macro",
    "vba": "VBA",


    # UI/UX DESIGN

    "figma": "Figma",
    "adobe xd": "Adobe XD",
    "sketch": "Sketch",
    "invision": "InVision",
    "zeplin": "Zeplin",
    "ui/ux": "UI/UX Design",
    "ui ux": "UI/UX Design",
    "ux design": "UI/UX Design",
    "ui design": "UI/UX Design",
    "user interface": "UI/UX Design",
    "user experience": "UI/UX Design",
    "wireframe": "Wireframing",
    "wireframing": "Wireframing",
    "prototyping": "Prototyping",
    "design thinking": "Design Thinking",


    # SOFT SKILLS

    "problem solving": "Problem Solving",
    "pemecahan masalah": "Problem Solving",
    "critical thinking": "Critical Thinking",
    "berpikir kritis": "Critical Thinking",
    "analitik": "Analytical Thinking",
    "analytical thinking": "Analytical Thinking",
    "analytical skill": "Analytical Thinking",
    "kemampuan analisis": "Analytical Thinking",
    "communication skill": "Communication",
    "komunikasi": "Communication",
    "teamwork": "Teamwork",
    "kerja tim": "Teamwork",
    "team player": "Teamwork",
    "attention to detail": "Attention to Detail",


    # DATA

    "data cleaning": "Data Cleaning",
    "pembersihan data": "Data Cleaning",
    "data wrangling": "Data Wrangling",
    "data manipulation": "Data Manipulation",
    "data modeling": "Data Modeling",
    "pemodelan data": "Data Modeling",
    "data governance": "Data Governance",
    "tata kelola data": "Data Governance",
    "data quality": "Data Quality",
    "kualitas data": "Data Quality",
    "data reconciliation": "Data Reconciliation",
    "rekonsiliasi data": "Data Reconciliation",
    "business intelligence": "Business Intelligence",
    "bi": "Business Intelligence",
    "financial analysis": "Financial Analysis",
    "analisis keuangan": "Financial Analysis",
    "financial modeling": "Financial Modeling",
    "roi analysis": "ROI Analysis",
    "kpi": "KPI",
    "key performance indicator": "KPI",


    # OTHERS

    "it support": "IT Support",
    "technical support": "Technical Support",
    "troubleshooting": "Troubleshooting",
    "helpdesk": "Help Desk",
    "help desk": "Help Desk",
    "active directory": "Active Directory",
    "ad": "Active Directory",
    "ldap": "LDAP",
    "sso": "SSO",
    "windows server": "Windows Server",
    "vmware": "VMware",
    "virtualbox": "VirtualBox",
    "virtualization": "Virtualization",
    "storage": "Storage Management",
    "backup": "Backup & Recovery",
    "disaster recovery": "Disaster Recovery",
    "itil": "ITIL",
    "cobit": "COBIT",
    "iso 9001": "ISO 9001",
}

Stopwords

In [ ]:
ENGLISH_STOPWORDS = set(stopwords.words("english"))

INDONESIAN_STOPWORDS_EXTRA = {
    "dan", "atau", "yang", "untuk", "dengan", "dalam", "pada", "dari",
    "ke", "di", "ini", "itu", "serta", "juga", "namun", "tetapi",
    "karena", "agar", "sehingga", "oleh", "terhadap", "antara",
    "tentang", "melalui", "secara", "sebagai", "tidak", "bisa",
    "dapat", "akan", "telah", "sudah", "sedang", "sangat", "lebih",
    "saat", "setiap", "sesuai", "atas", "bawah", "hal", "bidang",
    "tim", "hasil", "proses", "sistem", "informasi", "perusahaan",
    "pekerjaan", "kerja", "semua", "harus", "wajib",

    # HR words
    "mampu", "menguasai", "memiliki", "pengalaman", "kemampuan",
    "dibutuhkan", "diharapkan", "bertanggung", "jawab", "tugas",
    "kualifikasi", "persyaratan", "deskripsi", "jobdesk",
    "posisi", "jabatan", "melamar", "kandidat", "calon",
}

factory = StopWordRemoverFactory()
SASTRAWI_STOPWORDS = set(factory.get_stop_words())

INDONESIAN_STOPWORDS = INDONESIAN_STOPWORDS_EXTRA | SASTRAWI_STOPWORDS

ENGLISH_HR_WORDS = {
    "responsible", "qualification", "qualifications",
    "requirement", "requirements", "ability",
    "experience", "knowledge", "proficient",
    "work", "working", "must", "good", "strong",
    "preferred", "required", "year", "years",
}

ALL_STOPWORDS = (
    ENGLISH_STOPWORDS
    | INDONESIAN_STOPWORDS
    | ENGLISH_HR_WORDS
)

PROTECTED_TOKENS = {
    "sql", "r", "c", "go", "bi", "ai", "ml", "dl",
    "js", "ts", "api", "aws", "gcp"
}

Preprocessing

In [ ]:
def preprocess_text(text):

    if not isinstance(text, str) or not text.strip():
        return ""

    text = text.lower() # lowercase
    text = re.sub(r"http\S+|www\.\S+", " ", text) # hapus url
    text = re.sub(r"\S+@\S+", " ", text) # hapus email
    text = re.sub(r"[\\|(){}\[\]<>\"']", " ", text) # hapus simbol
    text = re.sub(r"\b\d+\b", " ", text) # hapus angka
    text = re.sub(r"[;:,\n\r\t]+", " ", text) # normalisasi separator
    text = re.sub(r"[!?*&%$@^=~`]", " ", text) # hapus simbol tambahan
    text = re.sub(r"\s+", " ", text).strip() # normalisasi spasi

    return text

In [ ]:
def remove_stopwords(text):

    tokens = text.split()

    filtered = []

    for token in tokens:
        if token in PROTECTED_TOKENS:
            filtered.append(token)
        elif token not in ALL_STOPWORDS and (
            len(token) > 2 or token in PROTECTED_TOKENS
        ):
            filtered.append(token)

    return " ".join(filtered)

In [ ]:
def full_preprocess(text):
    cleaned = preprocess_text(text)

    return remove_stopwords(cleaned)

In [ ]:
df["cleaned_text"] = df["deskripsi"].astype(str).apply(full_preprocess)

df[["deskripsi", "cleaned_text"]].head()

,deskripsi,cleaned_text
0,Kualifikasi\n:\nS1 Teknik Industri / Informati...,teknik industri informatika sains fresh gradua...
1,"Key Responsibilities\nBuild, maintain, and aut...",key responsibilities build maintain automate d...
2,Company Description\nAbout Grab and Our Workpl...,company description grab workplace grab southe...
3,Responsibilities:\nSupporting Accounting Divis...,responsibilities supporting accounting divisio...
4,Cimol Bojot AA (PT Citarasa Kuliner Indonesia)...,cimol bojot citarasa kuliner indonesia buildin...

Regex Pattern

In [ ]:
REGEX_PATTERNS = [
    # Bahasa pemrograman dengan simbol
    (r"\bc\+\+\b",                   "C++"),
    (r"\bc#\b",                      "C#"),
    (r"\b\.net\b",                   ".NET"),
    (r"\bnode\.?js\b",               "Node.js"),
    (r"\breact\.?js\b",              "React"),
    (r"\bvue\.?js\b",                "Vue.js"),
    (r"\bangular\.?js\b",            "Angular"),
    (r"\bnext\.?js\b",               "Next.js"),
    (r"\bnuxt\.?js\b",               "Nuxt.js"),
    (r"\bd3\.?js\b",                 "D3.js"),
    (r"\bexpress\.?js\b",            "Express.js"),
    (r"\bnest\.?js\b",               "NestJS"),
    # Database
    (r"\bpost\s?gre\s?sql\b",        "PostgreSQL"),
    (r"\bpost\s?gres\b",             "PostgreSQL"),
    (r"\bmy\s?sql\b",                "MySQL"),
    (r"\bms\s?sql\b",                "SQL Server"),
    (r"\bsql\s?server\b",            "SQL Server"),
    # BI Tools
    (r"\bpower\s?bi\b",              "Power BI"),
    (r"\bgoogle\s+data\s+studio\b",  "Looker Studio"),
    (r"\blooker\s+studio\b",         "Looker Studio"),
    # Microsoft
    (r"\bms\s+excel\b",              "Excel"),
    (r"\bmicrosoft\s+excel\b",       "Excel"),
    (r"\bms\s+office\b",             "Microsoft Office"),
    # REST API
    (r"\brest\s*ful\s*api\b",        "REST API"),
    (r"\brest\s*api\b",              "REST API"),
    # Machine Learning singkatan
    (r"\bdeep\s+learning\b",         "Deep Learning"),
    (r"\bmachine\s+learning\b",      "Machine Learning"),
    (r"\bnatural\s+language\s+processing\b", "NLP"),
    (r"\bcomputer\s+vision\b",       "Computer Vision"),
    # Data
    (r"\bdata\s+visualization\b",    "Data Visualization"),
    (r"\bdata\s+warehouse\b",        "Data Warehouse"),
    (r"\bdata\s+science\b",          "Data Science"),
    (r"\bdata\s+analysis\b",         "Data Analysis"),
    (r"\bdata\s+cleaning\b",         "Data Cleaning"),
    (r"\bdata\s+wrangling\b",        "Data Wrangling"),
    (r"\bdata\s+modeling\b",         "Data Modeling"),
    (r"\bdata\s+pipeline\b",         "Data Pipeline"),
    (r"\bdata\s+lake\b",             "Data Lake"),
    (r"\bdata\s+quality\b",          "Data Quality"),
    (r"\bdata\s+governance\b",       "Data Governance"),
    (r"\bbusiness\s+intelligence\b", "Business Intelligence"),
    (r"\bfinancial\s+analysis\b",    "Financial Analysis"),
    (r"\bfinancial\s+modeling\b",    "Financial Modeling"),
    (r"\bpenetration\s+test(?:ing)?\b", "Penetration Testing"),
    # Others
    (r"\bamazon\s+web\s+services?\b","AWS"),
    (r"\bgoogle\s+cloud\s+platform\b","GCP"),
    (r"\bmicrosoft\s+azure\b",       "Azure"),
    (r"\bci\s?/?\s?cd\b",           "CI/CD"),
    (r"\bgithub\s+actions?\b",       "GitHub Actions"),
    (r"\bgitlab\s+ci\b",             "GitLab CI/CD"),
    (r"\bspring\s*boot\b",           "Spring Boot"),
    (r"\bmicro\s*services?\b",       "Microservices"),
    (r"\bgit\s+hub\b",               "GitHub"),
    (r"\bgit\s+lab\b",               "GitLab"),
    (r"\betl\b",                     "ETL"),
    (r"\belt\b",                     "ELT"),
    # UI/UX
    (r"\bui\s*/?\s*ux\b",            "UI/UX Design"),
    (r"\buser\s+interface\b",        "UI/UX Design"),
    (r"\buser\s+experience\b",       "UI/UX Design"),
    (r"\bssl\s*/?\s*tls\b",          "SSL/TLS"),
    (r"\btcp\s*/?\s*ip\b",           "TCP/IP"),
]

Extractor

In [ ]:
DICT_KEYS_SORTED = sorted(
    SKILL_DICT.keys(),
    key=lambda x: len(x),
    reverse=True
)

FUZZY_THRESHOLD = 85
FUZZY_MIN_LEN = 5

Helper

In [ ]:
def _normalize(text: str) -> str:
    return re.sub(r"\s+", " ", text.lower().strip())


def _dedupe_ordered(skills: List[str]) -> List[str]:
    seen = set()
    result = []
    for s in skills:
        key = s.lower()
        if key not in seen:
            seen.add(key)
            result.append(s)
    return result

Skill Extraction

In [ ]:
def extract_skills(raw_text: str, use_fuzzy: bool = True) -> List[str]:
    if not isinstance(raw_text, str) or not raw_text.strip():
        return []

    #lowercase, hapus noise
    text = preprocess_text(raw_text)
    found_skills = []
    consumed_spans = []

    #Regex matching
    temp_text = text
    for pattern, canonical in REGEX_PATTERNS:
        for m in re.finditer(pattern, temp_text, re.IGNORECASE):
            found_skills.append(canonical)
            placeholder = " " * len(m.group())
            temp_text = temp_text[:m.start()] + placeholder + temp_text[m.end():]

    working_text = temp_text

    #Dictionary matching
    for key in DICT_KEYS_SORTED:
        if len(key) < 2:
            continue

        escaped = re.escape(key)
        pattern = r"(?<!\w)" + escaped + r"(?!\w)"
        for m in re.finditer(pattern, working_text, re.IGNORECASE):
            found_skills.append(SKILL_DICT[key])
            placeholder = " " * len(m.group())
            working_text = working_text[:m.start()] + placeholder + working_text[m.end():]

    #Fuzzy matching
    if use_fuzzy:
        tokens = [t for t in working_text.split() if len(t) >= FUZZY_MIN_LEN]
        unique_tokens = list(set(tokens))

        for token in unique_tokens:
            result = process.extractOne(
                token,
                DICT_KEYS_SORTED,
                scorer=fuzz.ratio,
                score_cutoff=FUZZY_THRESHOLD,
            )
            if result:
                matched_key, score, _ = result
                if not re.fullmatch(r"\d+", token):
                    found_skills.append(SKILL_DICT[matched_key])

    #Deduplikasi
    return _dedupe_ordered(found_skills)

Convert List ke String

In [ ]:
df["deskripsi"] = df["deskripsi"].apply(extract_skills)

df.head()

,posisi,deskripsi,level,cleaned_text,skills
0,data analyst,"[Data Visualization, SQL, Informatica]",entry,teknik industri informatika sains fresh gradua...,"[Data Visualization, SQL, Informatica]"
1,data analyst,"[Power BI, Data Analysis, Financial Analysis, ...",middle,key responsibilities build maintain automate d...,"[Power BI, Data Analysis, Financial Analysis, ..."
2,data analyst,"[Power BI, Data Quality, Business Intelligence...",senior,company description grab workplace grab southe...,"[Power BI, Data Quality, Business Intelligence..."
3,data analyst,"[Analytical Thinking, Excel Macro, Excel, InVi...",middle,responsibilities supporting accounting divisio...,"[Analytical Thinking, Excel Macro, Excel, InVi..."
4,data analyst,"[Power BI, Looker Studio, ETL, Excel, Reportin...",middle,cimol bojot citarasa kuliner indonesia buildin...,"[Power BI, Looker Studio, ETL, Excel, Reportin..."

In [ ]:
df_final = df[["posisi", "deskripsi", "level"]]

df_final.head()

         posisi                                          deskripsi   level
0  data analyst             [Data Visualization, SQL, Informatica]   entry
1  data analyst  [Power BI, Data Analysis, Financial Analysis, ...  middle
2  data analyst  [Power BI, Data Quality, Business Intelligence...  senior
3  data analyst  [Analytical Thinking, Excel Macro, Excel, InVi...  middle
4  data analyst  [Power BI, Looker Studio, ETL, Excel, Reportin...  middle

In [ ]:
df_final.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5169 entries, 0 to 5168
Data columns (total 3 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   posisi     5169 non-null   object
 1   deskripsi  5169 non-null   object
 2   level      5169 non-null   object
dtypes: object(3)
memory usage: 121.3+ KB

In [ ]:
df_final.to_csv("data_preprocessed.csv", index=False)